import maya.cmds as O

def CRTSET(*args):
    O.group( em=False, name= "Joints")
    O.group( em=False, name= "DontTouch")
    O.group( em=False, name= "AllGroups")
    O.parent("LTBK_Wheel_Skin", 'Joints') 
    O.parent("RTBK_Wheel_Skin", 'Joints') 
    O.parent("LTFR_Wheel_Skin", 'Joints') 
    O.parent("RTFR_Wheel_Skin", 'Joints') 
    O.circle( nr=(0, 0, 1), c=(0, 0, 0) ,n = "Main_ctrl")
    O.group( em=True, name= "Main_grp")
    O.circle( nr=(0, 0, 1), c=(0, 0, 0) ,n = "Offset_ctrl")
    O.group( em=False, name= "Offset_grp")
    O.parent("Offset_grp", 'Main_ctrl')  
    O.parent("Main_grp", 'AllGroups') 
    O.parent("Main_ctrl", 'Main_grp')
    O.circle( nr=(0, 0, 1), c=(0, 0, 0) ,n = "LTBK_Wheel_ctrl")
    O.group( em=False, name= "LTBK_Wheel_grp")
    O.circle( nr=(0, 0, 1), c=(0, 0, 0) ,n = "RTBK_Wheel_ctrl")
    O.group( em=False, name= "RTBK_Wheel_grp")
    O.circle( nr=(0, 0, 1), c=(0, 0, 0) ,n = "LTFR_Wheel_ctrl")
    O.group( em=False, name= "LTFR_Wheel_grp")
    O.circle( nr=(0, 0, 1), c=(0, 0, 0) ,n = "RTFR_Wheel_ctrl")
    O.group( em=False, name= "RTFR_Wheel_grp")
    #Body
    O.circle( nr=(0, 0, 1), c=(0, 0, 0) ,n = "body_ctrl")
    O.group( em=False, name= "body_grp")
    O.parent("body_grp", 'Main_grp')

    O.matchTransform("body_grp","Body_Skin")
    O.parentConstraint( "body_ctrl","Body_Skin" )
    O.parent("LTBK_Wheel_grp", 'Main_grp')
    O.parent("RTBK_Wheel_grp", 'Main_grp')
    O.parent("LTFR_Wheel_grp", 'Main_grp')
    O.parent("RTFR_Wheel_grp", 'Main_grp')

    O.matchTransform("LTBK_Wheel_grp","LTBK_Wheel_Skin")
    O.matchTransform("RTBK_Wheel_grp","RTBK_Wheel_Skin")
    O.matchTransform("LTFR_Wheel_grp","LTFR_Wheel_Skin")
    O.matchTransform("RTFR_Wheel_grp","RTFR_Wheel_Skin")

    O.parentConstraint( "LTBK_Wheel_ctrl","LTBK_Wheel_Skin" )
    O.parentConstraint( "RTBK_Wheel_ctrl","RTBK_Wheel_Skin" )
    O.parentConstraint( "LTFR_Wheel_ctrl","LTFR_Wheel_Skin" )
    O.parentConstraint( "RTFR_Wheel_ctrl","RTFR_Wheel_Skin" )
def CRTBSET(*args):
    O.select(d=True)
    O.joint(p=(822,310,-885), n="LTBK_Wheel_Skin")
    O.select(d=True)
    O.joint(p=(-822,310,-885), n="RTBK_Wheel_Skin")
    O.select(d=True)
    O.joint(p=(844,310,1740), n="LTFR_Wheel_Skin")
    O.select(d=True)
    O.joint(p=(-844,310,1740), n="RTFR_Wheel_Skin")
    O.select(d=True)
    O.joint(p=(0,500,0), n="Body_Skin")   


O.window()
O.columnLayout()
O.button( l='Create Base Setup', c=(CRTBSET) )
O.button( l='Create Full Setup', c=(CRTSET) )
O.showWindow()
